<script lang="ts">
	import { Check, Clipboard } from 'lucide-svelte';
	import Reveal from '$lib/components/ui/Reveal.svelte';

	let activeTab = $state<'sql' | 'prisma' | 'types'>('sql');
	let isCopied = $state(false);

	const codeSnippets = {
		sql: `-- PostgreSQL Schema Generated by AiKanAja\n\nCREATE TABLE "users" (\n  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  "email" VARCHAR(255) UNIQUE NOT NULL,\n  "name" VARCHAR(100),\n  "created_at" TIMESTAMP DEFAULT NOW()\n);\n\nCREATE TABLE "orders" (\n  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  "user_id" UUID REFERENCES "users"("id") ON DELETE CASCADE,\n  "total_amount" DECIMAL(10,2) NOT NULL,\n  "status" VARCHAR(50) DEFAULT 'PENDING',\n  "created_at" TIMESTAMP DEFAULT NOW()\n);\n\nCREATE INDEX "idx_orders_user" ON "orders"("user_id");`,
		prisma: `// schema.prisma Generated by AiKanAja\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\nmodel User {\n  id        String   @id @default(uuid())\n  email     String   @unique\n  name      String?\n  createdAt DateTime @default(now())\n  orders    Order[]\n}\n\nmodel Order {\n  id          String   @id @default(uuid())\n  userId      String\n  user        User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n  totalAmount Decimal\n  status      String   @default("PENDING")\n  createdAt   DateTime @default(now())\n}`,
		types: `// TypeScript Definitions Generated by AiKanAja\n\nexport interface User {\n  id: string;\n  email: string;\n  name?: string;\n  createdAt: Date;\n}\n\nexport interface Order {\n  id: string;\n  userId: string;\n  totalAmount: number;\n  status: 'PENDING' | 'PAID' | 'FAILED';\n  createdAt: Date;\n}`
	};

	function copyCode() {
		navigator.clipboard.writeText(codeSnippets[activeTab]);
		isCopied = true;
		setTimeout(() => (isCopied = false), 2000);
	}
</script>

<section id="playground" class="border-t border-slate-900 bg-slate-950/30 py-28 relative z-10">
	<div class="max-w-7xl mx-auto px-6 grid md:grid-cols-12 gap-12 items-center">
		<Reveal class="md:col-span-5 space-y-6">
			<h2 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-white leading-tight">
				Hasilkan Sintaks Skema <br />Siap Deploy
			</h2>
			<p class="text-slate-400 leading-relaxed">
				Dapatkan sintaks bersih ter-linting yang dapat langsung diunduh atau disalin ke code
				editor Anda. Bebas eror syntax, rapi, dan sesuai konvensi.
			</p>

			<div class="space-y-3 pt-2">
				<div class="flex items-center gap-3 text-sm text-slate-355">
					<div
						class="w-5 h-5 rounded-full bg-orange-600/10 border border-orange-600/20 flex items-center justify-center"
					>
						<Check class="w-3.5 h-3.5 text-orange-500" />
					</div>
					<span>Foreign Key & Index Ditambahkan Otomatis</span>
				</div>
				<div class="flex items-center gap-3 text-sm text-slate-355">
					<div
						class="w-5 h-5 rounded-full bg-orange-600/10 border border-orange-600/20 flex items-center justify-center"
					>
						<Check class="w-3.5 h-3.5 text-orange-500" />
					</div>
					<span>Output Kode Rapi & Sesuai Spesifikasi ORM</span>
				</div>
			</div>
		</Reveal>

		<Reveal delay={0.15}
			class="md:col-span-7 bg-slate-900/80 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl backdrop-blur-md"
		>
			<div
				class="flex items-center justify-between px-5 py-4 border-b border-slate-800/80 bg-slate-950/40"
			>
				<div class="flex gap-2">
					{#each (['sql', 'prisma', 'types'] as const) as key}
						<button
							onclick={() => (activeTab = key)}
							class="px-4 py-1.5 rounded-lg text-xs font-mono font-semibold transition-all {activeTab ===
							key
								? 'bg-orange-600/10 text-orange-500 border border-orange-600/20'
								: 'text-slate-400 hover:text-slate-200 border border-transparent'}"
						>
							{key === 'sql' ? 'schema.sql' : key === 'prisma' ? 'schema.prisma' : 'types.ts'}
						</button>
					{/each}
				</div>

				<button
					onclick={copyCode}
					class="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-200 transition-colors bg-slate-950/60 border border-slate-850 px-3 py-1.5 rounded-lg active:scale-95 cursor-pointer"
				>
					{#if isCopied}
						<Check class="w-3.5 h-3.5 text-orange-500" />
						<span class="text-orange-500 font-semibold">Tersalin!</span>
					{:else}
						<Clipboard class="w-3.5 h-3.5" />
						<span>Salin</span>
					{/if}
				</button>
			</div>

			<div
				class="p-6 font-mono text-xs leading-relaxed text-slate-400 bg-slate-950/20 overflow-x-auto min-h-64 select-text"
			>
				<pre class="text-slate-350">{codeSnippets[activeTab]}</pre>
			</div>
		</Reveal>
	</div>
</section>
