import { BadRequestException, InternalServerErrorException } from 'elysia-http-exception'
import {
  mapColumnType,
  formatDefault,
  toPascalCase,
  toCamelCase,
  toPrismaType,
  toPrismaDefault,
} from '../helpers/export.helper'

type SqlTarget = 'mysql' | 'postgresql' | 'sqlite'

interface ErdColumn {
  id: string
  name: string
  type: string
  primaryKey: boolean
  nullable: boolean
  unique: boolean
  defaultValue: string | null
  foreignKey: { table: string; column: string } | null
}

interface ErdTable {
  id: string
  name: string
  position: { x: number; y: number }
  columns: ErdColumn[]
}

interface ErdRelation {
  id: string
  sourceTableId: string
  targetTableId: string
  sourceColumn: string
  targetColumn: string
  type: 'one-to-one' | 'one-to-many' | 'many-to-many'
}

interface ErdSchema {
  tables: ErdTable[]
  relations: ErdRelation[]
}

export class ExportService {
  /**
   * Generate SQL DDL dari ErdSchema.
   * - CREATE TABLE untuk setiap tabel
   * - PRIMARY KEY, NOT NULL, UNIQUE, DEFAULT constraints
   * - Foreign key constraints
   * - Type mapping sesuai target database
   */
  toSqlDdl(schema: ErdSchema, target: SqlTarget = 'postgresql'): string {
    try {
      const lines: string[] = []

      lines.push(`-- Generated by AiKanAja`)
      lines.push(`-- Target: ${target.toUpperCase()}`)
      lines.push(`-- Date: ${new Date().toISOString()}`)
      lines.push('')

      for (const table of schema.tables) {
        lines.push(this.buildCreateTable(table, target))
      }

      const fkStatements = this.buildForeignKeys(schema)
      if (fkStatements) {
        lines.push('-- Foreign Key Constraints')
        lines.push(fkStatements)
      }

      return lines.join('\n')
    } catch (err) {
      if (err instanceof Error && 'statusCode' in err) throw err
      console.error('[ExportService.toSqlDdl]', err)
      throw new InternalServerErrorException('Failed to generate SQL DDL')
    }
  }

  /**
   * Generate Prisma schema dari ErdSchema.
   * - Model definitions dengan Prisma types
   * - Relations dengan @relation
   */
  toPrismaSchema(schema: ErdSchema): string {
    try {
      const lines: string[] = []

      lines.push(`// Generated by AiKanAja`)
      lines.push(`// Date: ${new Date().toISOString()}`)
      lines.push('')
      lines.push('generator client {')
      lines.push('  provider = "prisma-client-js"')
      lines.push('}')
      lines.push('')
      lines.push('datasource db {')
      lines.push('  provider = "postgresql"')
      lines.push('  url      = env("DATABASE_URL")')
      lines.push('}')
      lines.push('')

      for (const table of schema.tables) {
        lines.push(this.buildPrismaModel(table))
      }

      return lines.join('\n')
    } catch (err) {
      console.error('[ExportService.toPrismaSchema]', err)
      throw new InternalServerErrorException('Failed to generate Prisma schema')
    }
  }

  // --- Private helpers ---

  private buildCreateTable(table: ErdTable, target: SqlTarget): string {
    const lines: string[] = []
    lines.push(`CREATE TABLE "${table.name}" (`)

    const columnDefs = table.columns.map(col => {
      const parts = [`  "${col.name}"`, mapColumnType(col.type, target)]

      if (col.primaryKey) parts.push('PRIMARY KEY')
      if (!col.nullable && !col.primaryKey) parts.push('NOT NULL')
      if (col.unique && !col.primaryKey) parts.push('UNIQUE')
      if (col.defaultValue && !col.primaryKey) {
        parts.push(`DEFAULT ${formatDefault(col.defaultValue, target)}`)
      }

      return parts.join(' ')
    })

    lines.push(columnDefs.join(',\n'))
    lines.push(');')
    lines.push('')

    return lines.join('\n')
  }

  private buildForeignKeys(schema: ErdSchema): string | null {
    const fkLines: string[] = []

    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.foreignKey) {
          fkLines.push(
            `ALTER TABLE "${table.name}" ADD CONSTRAINT "fk_${table.name}_${col.name}" ` +
            `FOREIGN KEY ("${col.name}") REFERENCES "${col.foreignKey.table}"("${col.foreignKey.column}");`
          )
        }
      }
    }

    return fkLines.length > 0 ? fkLines.join('\n') : null
  }

  private buildPrismaModel(table: ErdTable): string {
    const lines: string[] = []
    lines.push(`model ${toPascalCase(table.name)} {`)

    for (const col of table.columns) {
      const parts = [`  ${toCamelCase(col.name)}`, toPrismaType(col.type)]

      if (col.primaryKey) parts.push('@id @default(uuid())')
      if (col.unique && !col.primaryKey) parts.push('@unique')
      if (col.defaultValue && !col.primaryKey) {
        parts.push(`@default(${toPrismaDefault(col.defaultValue)})`)
      }
      if (col.foreignKey) {
        parts.push(`@relation(fields: [${toCamelCase(col.name)}], references: [${toCamelCase(col.foreignKey.column)}])`)
      }

      lines.push(parts.join(' '))
    }

    lines.push('}')
    lines.push('')

    return lines.join('\n')
  }
}
